### ISSUE TITLE
Printing of error messages shown as [object Object]

### ISSUE THREAD

**Issue by mebibou** [bsorrentino/cordova-broadcaster#10]
Error messages are not printed out correctly, i.e. it would be better to print messages like `console.error('Error', error)` as Chrome would print out the error object instead of printing `[object Object]`.

I am talking about [line 39](https://github.com/bsorrentino/cordova-broadcaster/blob/master/www/broadcaster.js#L39) and [line 52](https://github.com/bsorrentino/cordova-broadcaster/blob/master/www/broadcaster.js#L52)

**Comment by bsorrentino** [comment]
Hi thx for feedback

You right, I'll fix it soon

**Comment by bsorrentino** [comment]
I've released version 2.0.7 with fix

try it and let me know

**Comment by mebibou** [comment]
Changes look good.

Fyi to reference an issue in a commit message you should use the syntax `fixes #10` instead, so that the commit will actually be referenced in the issue feed.

**Comment by bsorrentino** [comment]
thx for feedback
