### ISSUE TITLE
Why use this plugin compile failed.

### ISSUE THREAD

**Issue by csrbzhb** [bsorrentino/cordova-broadcaster#11]
Property 'broadcaster' does not exist on type 'Window'.

      L21:  ) {
      L22:    window.broadcaster.addEventListener("didShow", function (e) {

**Comment by bsorrentino** [comment]
Hi

Such error means that something in the plugin/cordova installation has gone wrong!

**Comment by bsorrentino** [comment]
closed for inactivity
