### ISSUE TITLE
Battery mode

### ISSUE THREAD

**Issue by pooi-pooi** [bsorrentino/cordova-broadcaster#14]
Hello guys, can I get the current Battery Mode (normal, low power mode)?

**Comment by bsorrentino** [comment]
Probably you need [cordova-plugin-battery-status](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-battery-status/)

**Comment by pooi-pooi** [comment]
cordova-plugin-battery-status dont help me, because its give me the power level.

Can I use cordova-broadcaster to observes **NSProcessInfoPowerStateDidChangeNotification**?

https://developer.apple.com/library/content/documentation/Performance/Conceptual/EnergyGuide-iOS/LowPowerMode.html

**Comment by bsorrentino** [comment]
Ok

I've understood the problem and this plugin could easily allows what u need

From native side register an handler on NSProcessInfoPowerStateDidChangeNotification, in such handler test your state and notify such info using another your custom pre-defined event (e.g. PowerStayeDidChange) to the JavaScript where you have added a listener

**Comment by pooi-pooi** [comment]
That`s really good!
Do you have any sample?

**Comment by bsorrentino** [comment]
I'll provide you code snippet asap

**Comment by pooi-pooi** [comment]
I am very grateful

**Comment by bsorrentino** [comment]
I've published sample  [here](https://gist.github.com/bsorrentino/ac2b3ee2cecb96a867f6d922faa90617) 

The sample consists of a cordova plugin (`broadcasterTest .m / .js`) that setup the notification and give you current state at startup.

**Comment by pooi-pooi** [comment]
you are awesome!
