### ISSUE TITLE
a bit more info on this plogin please

### ISSUE THREAD

**Issue by adamgins** [bsorrentino/cordova-broadcaster#16]
Hi there, 

can you please  provide some example/infos where this plugin would be useful. 

I am trying to voice activate my Cordova app and wanted to see if this plugin would help with that.

thanks

**Comment by bsorrentino** [comment]
Hi, thanks for interest 

Could you provide me a bit of info more concerning your use case so I can give you a complete sample ?

**Comment by adamgins** [comment]
Thanks. Sure

User is driving in the car and "Says hey siri, open <AppName> and do <something>"

something = something app specific, eg "add a task"... that the App would know how to process.

I understand that iOS (not sure about Android) intents are fairly restricted... ie would probably have to use "Message". 

I currently have the commands working with sirkit, but it requires a user to click a button in the app to start Siri, which I don't want... ie I want pure voice control.

Any ideas welcome.

thanks again

**Comment by bsorrentino** [comment]
Looks very interesting 

This is a bit more complex as I imaged ... and i think that plugin could be useful when we have understood **if is possible** / **how start** SIRI using a message

**Comment by bsorrentino** [comment]
closed for inactivity
