### ISSUE TITLE
Listening system events? 

### ISSUE THREAD

**Issue by MladeM** [bsorrentino/cordova-broadcaster#19]
Can one use this plugin to listen for system events, such as locking and unlocking of a device?

**Comment by bsorrentino** [comment]
Such plugin is very flexible and you could use it in a lot of use cases .

However the answer is yes you can.

I don't know your use case but you can also take a look to [cordova-plugin-lock-info](https://www.npmjs.com/package/cordova-plugin-lock-info) or [cordova-plugin-screen-locker](https://github.com/kitolog/cordova-plugin-screen-locker)

**Comment by bsorrentino** [comment]
Closed due inactivity
