### ISSUE TITLE
Cordova5.0.0 this.webView.evaluateJavascript has removed in android!!!

### ISSUE THREAD

**Issue by arist1213** [bsorrentino/cordova-broadcaster#2]
Android compiler error.
Any idea how to fix this?

**Comment by bsorrentino** [comment]
thx for feedback

It seems that the method evaluateJavascript(...) has been removed from the Cordova 5.0.0 

Seems that webView.sendJavascript(js) replace evaluateJavascript()

I'll fix soon

**Comment by arist1213** [comment]
haha,  I need to implement a third part push service, then I found here.

the iOS works perfect, but java block me.  thank you for your support.

I am also looking for the solutions.

**Comment by bsorrentino** [comment]
I've deployed version 2.0.0 with fix

could you test it and let me know ?

Thanks in advance

**Comment by arist1213** [comment]
Yes, I just test in android, it's worked. Great work!!!
