### ISSUE TITLE
Is it possible to receive a broadcast from an external native Android app to an Ionic2 app using this plugin?

### ISSUE THREAD

**Issue by anghiulian** [bsorrentino/cordova-broadcaster#20]
If not, would it be possible to use the plugin and rewrite the plugin to use the global broadcast manager instead of the local one?

**Comment by bsorrentino** [comment]
Take a look comments on issue #17

**Comment by anghiulian** [comment]
I looked over the #17 issue but there are some things that are not clear to me. This is the full scenario that I am talking about:
- App1 is a Native Android app that sends broadcast globaly to other apps, some native some Cordova(Ionic2)
-App2 is a full fledged Ionic2 app that should receive the global broadcast from App1.

Considering the scenario above, I don't think the solution from #17 is feasible.
App2 should subscribe to certain global broadcasts in order to receive them. That's why I asked previously if you ever tried a variant of the library, with global subscribe for broadcast.

**Comment by bsorrentino** [comment]
I haven't planned to do it yet.

My suggestion is to register handler from external event natively in the ionic app and inside that handler you could send local notification using broadcaster plugin ( it is much less complex than seems)

**Comment by bsorrentino** [comment]
closed for inactivity
