### ISSUE TITLE
addEventListner does not get called back in ios

### ISSUE THREAD

**Issue by Prabuganesan** [bsorrentino/cordova-broadcaster#21]
This is my code in ionic.

```javascript
constructor(public navCtrl: NavController,public broadcaster: Broadcaster,private platform: Platform) 
{
   this.platform.ready().then(() => {
     console.log('Ready')
     this.broadcaster.addEventListener('postevent')
       .subscribe((Event) => console.log('After post ionic'));

      this.broadcaster.fireNativeEvent('eventName', {}).then(() => console.log('After fire ionic'));
   });
```
And i have add following code in native side. In MainViewController 

```objective-c
 (void)viewDidLoad
{
    [super viewDidLoad];
     [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(navigateFromPlugin) name:@"eventName" object:nil];
    // Do any additional setup after loading the view from its nib.
}
-(void)navigateFromPlugin
{
    NSLog(@"Print Native **************");
    
    [[NSNotificationCenter defaultCenter] postNotificationName:@"postevent" object:self];

}
```
This code not working. 'After post ionic' log not printed.

**Comment by bsorrentino** [comment]
Hi 

1. Are you using last version  **2.2.1** ?
2. you don't see log _'After post ionic'_, but do you see  _"Print Native **************"_ ?

**Comment by Prabuganesan** [comment]
Hi, Ya I used latest version. I see Print Native **************. But not 'After post ionic' in log.

**Comment by bsorrentino** [comment]
Seems a problem related to workflow synchronization. 

Probably the _navigateFromPlugin_ is called before plugin register the native listener.

Let me know if it is possible

**Comment by Prabuganesan** [comment]
Approximately how much time taken for plugin register the native listener.

**Comment by bsorrentino** [comment]
I think that is a problem due the Gand Central Dispatch (GCD)

Try this:

```objective-c
 dispatch_async(dispatch_get_main_queue(), ^{ 
   [[NSNotificationCenter defaultCenter] postNotificationName:@"postevent" object:self];
 });

```
and let me know

**Comment by Prabuganesan** [comment]
Already I tried this. But not working.

**Comment by bsorrentino** [comment]
the question is ... what NSTimer do ?

I've to investigate

**Comment by Prabuganesan** [comment]
ok..

**Comment by bsorrentino** [comment]
Is it possible share the code in order I could replicate the problem ?

**Comment by Prabuganesan** [comment]
Here I attache my project. Please check this.
[ionic-native-listioner.zip](https://github.com/bsorrentino/cordova-broadcaster/files/1155423/ionic-native-listioner.zip)

**Comment by bsorrentino** [comment]
thx for sharing

**Comment by Prabuganesan** [comment]
Thanks for your response. Please fix this bug ASAP.

**Comment by bsorrentino** [comment]
I've understood the problem 

The javascript method `this.broadcaster.addEventListener` is asynchronous (i.e. add listener after cordova exec success) so the subsequent call to `this.broadcaster.fireNativeEvent` is performed while the listener is not subscribed yet

To remove this condition I have to rethink the API and, due that your use case is not the most common one, I'll suggest you to use the simple _work around_ below

```javascript
   this.platform.ready().then(() => {
       console.log('Ready');

       this.broadcaster.addEventListener('postevent')
        .subscribe( (event) => console.log('After post ionic') );

        setTimeout( ()=> {
          this.broadcaster.fireNativeEvent('eventName', {})
                  .then(() => console.log('After fire ionic'));
        },0);

    });

```

**Comment by Prabuganesan** [comment]
ok thanks @bsorrentino

**Comment by bsorrentino** [comment]
Thanks you for feedbacks

Hope this issue don't discourage you to use plugin
