### ISSUE TITLE
How to stop broadcaster in ionic app?There is no API available?It consume more battery?

### ISSUE THREAD

**Issue by Prabuganesan** [bsorrentino/cordova-broadcaster#22]

**Comment by bsorrentino** [comment]
I'm not sure what do you mean for **stop broadcaster**. 

However the plugin provide a `removeEventListener` to unsubscribe (*and eventually remove*) subscription

**Comment by Prabuganesan** [comment]
Thanks.. I'm using @ionic-native/broadcaster plugin in ionic 3. 'removeEventListener' method not available. Can u please help me....

**Comment by bsorrentino** [comment]
keep in mind that `ionic-native/broadcaster`wraps original methods. 
In particular, in the `ionic-native/broadcaster`, the `addEventListener(eventName: string): Observable<any>` return an **Observable**  and the `removeEventListener` is implicit in Observable **unsubscription** than you can use that to stop broadcaster. 

### register subscription
```javascript

let subscription = this.broadcaster.addEventListener('eventName')
                                       .subscribe((event) => console.log(event));
```

### when you need to stop

```javascript

subscription.unsubscribe();

```

**Comment by Prabuganesan** [comment]
Thanks for your clarification..
