### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by Desever** [bsorrentino/cordova-broadcaster#27]
how to start

**Comment by bsorrentino** [comment]
Could you be more specific ? What you have to do ?

I guess that you have an [cordova](https://cordova.apache.org/) project and you have add this plugin `cordova plugin add cordova-plugin-broadcaster`

**Comment by tushe** [comment]
Hi, I have to catch volume up press when my app is in background, is it possible with this plugin? And when screen is locked? Thanks!

**Comment by bsorrentino** [comment]
To catch volume up in background or when screen locked concerns the native capabilitIes of mobile OS 

This plugin is able to notify a native event to web UI but, in the above cases, there isn’t an active UI so I don’t think that it could be useful

**Comment by bsorrentino** [comment]
closed for inactivity
