### ISSUE TITLE
broadcaster extras are missing

### ISSUE THREAD

**Issue by schinnaraju** [bsorrentino/cordova-broadcaster#30]
let listener = function( e ) {
      console.log('barcode :: ' + JSON.stringify(e));
    }
    window.broadcaster.addEventListener( "BarcodeReader", listener);

Android code 
    Intent intentVal = new Intent("BarcodeReader");                 
    Bundle b = new Bundle();                 
    b.putString( "barcode", content+"");               
    b.putString( "userdata", "{ \"data\": \"test\"}" );                 
    intent.putExtras( b);                   
    LocalBroadcastManager.getInstance(MainActivity.this).sendBroadcastSync(intentVal);

but e prints as {} instead of actual data.

**Comment by bsorrentino** [comment]
Hi, thanks for feedback

In android the plugin retrieves extended data from the intent named `userdata` as shown below

```java
final Bundle b = intent.getExtras();

// parse the JSON passed as a string.

String userData = b.getString("userdata", "{}");
```

**Comment by schinnaraju** [comment]
The broadcast work but the extra data are empty when i parse from Javascript code. Is there anything missing in the code (I have updated with native code as well)

**Comment by bsorrentino** [comment]
what does you mean with `extra` ?. As wrote above the plugin (by deafult) extracts only field `userdata` from extras

**Comment by schinnaraju** [comment]
i mean am not getting "userdata"

**Comment by bsorrentino** [comment]
Ok got it

Let me check

**Comment by bsorrentino** [comment]
One of reason could be that the string passed to extra is not valid json object

**Comment by bsorrentino** [comment]
check out the new version `2.4.0` it not use `userdata` anymore
