### ISSUE TITLE
Android: return all Intent extra data

### ISSUE THREAD

**Issue by bsorrentino** [bsorrentino/cordova-broadcaster#31]
Like plugin [com-darryncampbell-cordova-plugin-intent](https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent) the cordova-broadcaster will not return exclusively the `userdata` extra field but all extra fields 

*Challenge:*
> Keep backward compatibility

**Comment by bsorrentino** [comment]
The backward compatibility has been broken, the field `userdata` is no longer used

**Comment by mebibou** [comment]
@bsorrentino when you do breaking changes like that, please release a major version not a minor one... all my apps stopped working and realized it's because of this change, even though my dependency is set as `^2.1.0`. Please remove `2.4.0` and post as `3.0.0`

**Comment by bsorrentino** [comment]
Hi

You right, sorry about that 

- Removed version `2.4.0`
- Removed tag `2.4.0`
- Published version `3.0.0`

Thanks for using such plugin
