### ISSUE TITLE
removeEventListener does not remove event key #15

### ISSUE THREAD

**Issue by schinnaraju** [bsorrentino/cordova-broadcaster#32]
This issue is still (see #15) am having with latest version as well. I am not able to remove the listener. Since am using the same with multiple places with different purpose hence i want to remove from one page and add at another page (ionic 2 project)

**Comment by bsorrentino** [comment]
Are you using [ionic-native](https://ionicframework.com/docs/native/broadcaster/) implementation ?

If yes, you have to use unsubscribe to remove listener 

```javascript
let subscription = this.broadcaster.addEventListener('eventName').subscribe((event) => console.log(event));

// when you need 

subscription.unsubscribe();
```

**Comment by bsorrentino** [comment]
@schinnaraju

I've developed an ionic3 sample project using broadcaster [https://github.com/bsorrentino/ionic-broadcaster-sample]() that shows how to remove listener

**Comment by qingmengwuhen** [comment]
I resolved this question as following:   When i leave current page,   `window.broadcaster._channels = {};`
