### ISSUE TITLE
Fire intent debugging in fireNativeEvent

### ISSUE THREAD

**Issue by p4bl1t0** [bsorrentino/cordova-broadcaster#33]
I'm using the following code to trigger the GTALK heartbeat in order to maitain the GCM socket open.

```
window.broadcaster.fireNativeEvent("com.google.android.intent.action.GTALK_HEARTBEAT", {}, function () {
    console.log("GTALK_HEARTBEAT fired");
}, function (e, a) {
    console.log("GTALK_HEARTBEAT error", e, a);
});
```

In the web console and logcat I'm seeing the "GTALK_HEARTBEAT fired" but not any mentions to the intent of being fire. Is this normal?

Could you help me to debug this?

**Comment by bsorrentino** [comment]
Hi

I see in your code example that you pass nothing attached to event `{}`.
If you use  `fireNativeEvent` I guess that you have a BroadcastReceiver where you got the intent. 
Remember that, in this version of plugin, the JSON from javascript is stored as string into field `userdata` of the intent, at now check there if data arrive correcly

You right, there isn't logging information about Intent, I'll add it in the next version that i'm arranging

**Comment by bsorrentino** [comment]
closed for inactivity
