### ISSUE TITLE
Listen volume buttons click

### ISSUE THREAD

**Issue by bionner** [bsorrentino/cordova-broadcaster#38]
Hi i need to subscribe my app to the volume buttons click event, but i dont know what's the event name i have to subscribe, there's a list event i can check? 

In the ionic native docs: 

// Listen to events from Native
**this.broadcaster.addEventListener('eventName').subscribe((event) => console.log(event));**

Greetings!!

**Comment by bsorrentino** [comment]
Hi @bionner 

This plugin is an enabler to exchange events between native & web

The name of events  that you want manage doesn’t concern the plugin but the application that use it

Anyway if you give me more details I could help to solve your problem

**Comment by bsorrentino** [comment]
Hi @bionner 

This plugin is an enabler to exchange events between native & web 

In your case I think that you have to manage entire workflow in native code .. I don't see any implication with web part of your app ...  is it so ?

**Comment by bsorrentino** [comment]
closed due inactivity

**Comment by thiagobrez** [comment]
If someone ever needs it again, I wrote a Capacitor plugin for listening to volume button clicks:
https://github.com/thiagobrez/capacitor-volume-buttons
