### ISSUE TITLE
Adding Windows support by including BroadcasterProxy.js?

### ISSUE THREAD

**Issue by jeremyosterhoudt** [bsorrentino/cordova-broadcaster#40]
Given Cordova for Windows is WinJS, has consideration been given to adding the windows platform that would simply include the BroadcasterProxy.js?

If this would be an OK addition I would be happy to do a PR to add and test it.

**Comment by bsorrentino** [comment]
Hi @jeremyosterhoudt 
I agree ... please go ahead

**Comment by bsorrentino** [comment]
Closed due inactivity
