### ISSUE TITLE
[IOS]the Broadcaster plugin is not installed.

### ISSUE THREAD

**Issue by jlopezuc** [bsorrentino/cordova-broadcaster#41]
Hello,

I try to use the Broadcaster in IOS, but I always have the same error:

[Warning] Native: I tried to call Broadcaster.addEventListener, but the Broadcaster plug-in is not installed. (vendor.js, line 72225)
[Warning] Install the Broadcaster plugin: 'ionic cordova plugin add cordova-plugin-broadcaster' (vendor.js, line 72231)
[Warning] Native: I tried to call Broadcaster.removeEventListener, but the Broadcaster plug-in is not installed. (vendor.js, line 72225)
[Warning] Install the Broadcaster plugin: 'ionic cordova plugin add cordova-plugin-broadcaster' (vendor.js, line 72231)
[Error] ERROR - Error: plugin_not_installed

on Android works well

I use the latest version of the plugin and the latest version of @ ionic-native / broadcaster

What could be wrong?

Thanks

**Comment by bsorrentino** [comment]
`[Warning] Native: I tried to call Broadcaster.addEventListener, but the Broadcaster plug-in is not installed. (vendor.js, line 72225)`

Seems that plugin is not installed on IOS platform ...

**Comment by bsorrentino** [comment]
do you have to complete uninstall it and reinstall ?

**Comment by jlopezuc** [comment]
Yes, I Did

**Comment by bsorrentino** [comment]
Are you waiting for deviceready to fire before you call any plugin functions?

**Comment by bsorrentino** [comment]
can you share code ?

**Comment by jlopezuc** [comment]
Hi,

i cant share code, but i can show you the package.json and a example to call the plugin

I had to deleted the private info to the package.json for share you the code qith you:

`{
  "name": "",
  "version": "1.1.2",
  "author": "",
  "homepage": "",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "env=dev ionic-app-scripts build --prod",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "cross-env env=ionic ionic build",
    "ionic:serve": "cross-env env=ionic ionic serve",
    "android:run": "env=dev ionic cordova run android",
    "android:build": "env=dev ionic cordova build android",
    "android:run:dev": "env=dev ionic cordova run android --prod",
    "android:build:dev": "env=dev ionic cordova build android --prod",
    "android:run:pre": "env=pre ionic cordova run android",
    "android:build:pre": "env=pre ionic cordova build android --prod --release",
    "android:run:pro": "env=prod ionic cordova run android --prod",
    "android:build:pro": "env=prod ionic cordova build android --prod --release"
  },
  "dependencies": {
    "@agm/core": "^1.0.0-beta.3",
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@angular/router": "^5.2.11",
    "@ionic-native/android-permissions": "^4.5.2",
    "@ionic-native/app-version": "^4.7.0",
    "@ionic-native/broadcaster": "^4.5.3",
    "@ionic-native/camera": "^4.14.0",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/date-picker": "^4.5.3",
    "@ionic-native/device": "^4.5.3",
    "@ionic-native/diagnostic": "^4.10.1",
    "@ionic-native/document-viewer": "^4.9.1",
    "@ionic-native/file": "^4.9.1",
    "@ionic-native/file-opener": "^4.9.1",
    "@ionic-native/flurry-analytics": "^4.12.2",
    "@ionic-native/http": "^4.12.2",
    "@ionic-native/in-app-browser": "^4.5.3",
    "@ionic-native/local-notifications": "^4.5.3",
    "@ionic-native/network": "^4.5.3",
    "@ionic-native/push": "^4.5.3",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/pro": "1.0.20",
    "@ionic/storage": "^2.1.3",
    "@mobiscroll/angular": "file:./mobiscroll-angular-4.2.3.tgz",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^2.0.1",
    "@types/chart.js": "^2.7.7",
    "@types/chartist": "^0.9.38",
    "@types/cordova-plugin-app-version": "^0.1.35",
    "@types/cordova-plugin-camera": "^2.4.0",
    "@types/cordova-plugin-file": "^4.3.2",
    "@types/cordova-plugin-file-opener2": "^2.0.0",
    "@types/cordova-sqlite-storage": "^1.5.3",
    "@types/cordova.plugins.diagnostic": "^3.7.0",
    "@types/lodash": "^4.14.106",
    "chart.js": "^2.7.1",
    "chartist": "^0.11.0",
    "com.testfairy.cordova-plugin": "^2.14.0",
    "cordova-android": "6.3.0",
    "cordova-ios": "4.5.5",
    "cordova-plugin-add-swift-support": "^1.7.1",
    "cordova-plugin-advanced-http": "^2.0.1",
    "cordova-plugin-android-permissions": "^1.0.0",
    "cordova-plugin-app-event": "^1.2.1",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-broadcaster": "^3.1.1",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-cocoapod-support": "^1.6.0",
    "cordova-plugin-datepicker": "^0.9.3",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-document-viewer": "^0.9.10",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-opener2": "^2.0.19",
    "cordova-plugin-flurryanalytics": "^1.4.6",
    "cordova-plugin-inappbrowser": "^2.0.2",
    "cordova-plugin-ionic": "4.1.7",
    "cordova-plugin-ionic-webview": "1.2.1",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-opentok": "3.3.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.4.0",
    "cordova-uxcam": "^2.3.7",
    "cordova.plugins.diagnostic": "^4.0.10",
    "cross-env": "^5.1.3",
    "de.appplant.cordova.plugin.local-notification": "^0.8.5",
    "intl": "^1.2.5",
    "ion": "1.0.1",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic2-calendar": "^0.4.2",
    "ionicons": "3.0.0",
    "ios-deploy": "^1.9.3",
    "lodash": "^4.17.5",
    "moment": "^2.20.1",
    "ng-chartist": "^1.1.1",
    "phonegap-plugin-push": "^1.11.1",
    "roboto-fontface": "^0.9.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "xml2js": "^0.4.19",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.1.8",
    "typescript": "2.4.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-android-permissions": {},
      "cordova-sqlite-storage": {},
      "cordova-plugin-app-event": {},
      "de.appplant.cordova.plugin.local-notification": {},
      "phonegap-plugin-push": {
        "SENDER_ID": ""
      },
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-broadcaster": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-datepicker": {},
      "cordova-plugin-ionic": {
        "APP_ID": "",
        "CHANNEL_NAME": "develop",
        "UPDATE_METHOD": "none",
        "WARN_DEBUG": "true",
        "UPDATE_API": "https://api.ionicjs.com",
        "MAX_STORE": "2"
      },
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-app-version": {},
      "com.testfairy.cordova-plugin": {},
      "cordova.plugins.diagnostic": {},
      "cordova-plugin-document-viewer": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-opener2": {},
      "cordova-plugin-flurryanalytics": {},
      "cordova-uxcam": {},
      "cordova-plugin-opentok": {},
      "cordova-plugin-advanced-http": {},
      "cordova-plugin-camera": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  },
  "config": {
    "ionic_webpack": "./config/webpack.config.js",
    "ionic_copy": "./scripts/copy-mobiscroll-css.js"
  }
}
`

and the example call is:

`
initializeApp() {
    this.platform.ready().then(() => {
        if (this.platform.is('cordova')) {
            this.broadcaster.addEventListener(`${CONSTANTS.eventos.spirometerInformationFlow}`).subscribe(event => {
                console.log(event);
            });
        }
    });
}
`

**Comment by bsorrentino** [comment]
Thank for sharing ..... 

It is very hard to make a diagnosis ... on my sample project  [ionic-broadcaster-sample|https://github.com/bsorrentino/ionic-broadcaster-sample] all seems work well

have you tried to remove/add IOS platform again ?

**Comment by bsorrentino** [comment]
closed due inactivity
