### ISSUE TITLE
Is it possible to get current media volume of Android and iOS phone inside of Ionic 3 app?

### ISSUE THREAD

**Issue by maksimovicnikola** [bsorrentino/cordova-broadcaster#43]

**Comment by bsorrentino** [comment]
this plugin is an enabler that provide a way to exchange messages between native and web.

I'm pretty sure that there is a way to get a media volume ... in that case this plugin could be useful to send such info to web through a message

**Comment by bsorrentino** [comment]
Closed due inactivity
