### ISSUE TITLE
Why `sendBroadcastSync` over `sendBroadcast`?

### ISSUE THREAD

**Issue by Dragas** [bsorrentino/cordova-broadcaster#44]
In the example you suggest using `sendBroadcastSync`, but documentation suggests that it's a blocking operation. How come you suggest using it over the regular version of that call?

**Comment by bsorrentino** [comment]
Hi @Dragas 

`sendBroadcastSync` vs `sendBroadcast` is like `synchronous` vs `asynchronous` and for sure this will involve the thread on which the message will be processed.

However the plugin forces execution within UIThread so you can use which you prefer depending on youse use case

hope this help

**Comment by bsorrentino** [comment]
closed for inactivity
