### ISSUE TITLE
What is {"isTrusted": false} being appended in the listener?

### ISSUE THREAD

**Issue by semerda** [bsorrentino/cordova-broadcaster#45]
`var listener = function( e ) {
            //log: didShow received! userInfo: {"data":"test"}
            alert( "didShow received! userInfo: " + JSON.stringify(e)  );
        }`

Appears to returns:
{"isTrusted": false}

Prefixed inside the response object from my iOS NSNotificationCenter post. I'm assuming it might have something to do with trusting the broadcaster?

**Comment by bsorrentino** [comment]
Hi @semerda probably such field is added by NotificationCenter itself.

I'll investigate bit more

**Comment by bsorrentino** [comment]
Hi @semerda  this header seems automatically generated by native event infrastructure
