### ISSUE TITLE
Json for android is introducing "namevaluepairs" as key

### ISSUE THREAD

**Issue by alejouribesanchez** [bsorrentino/cordova-broadcaster#48]
![androidissue](https://user-images.githubusercontent.com/3950665/70180346-d19b7180-16ad-11ea-8b04-ab61d255e4da.png)

**Comment by bsorrentino** [comment]
I've found on [Stackoverflow](https://stackoverflow.com/questions/28405545/strange-namevaluepairs-key-appear-when-using-gson) that the problem is in JSON translation

**Comment by bsorrentino** [comment]
Hi @alejouribesanchez 

I'm not able to replicate the problem. Please, could you provide me a sample of code that cause error ?

**Comment by alejouribesanchez** [comment]
I will provide you this week

**Comment by bsorrentino** [comment]
Closed due inactivity
