### ISSUE TITLE
Accept external program broadcast

### ISSUE THREAD

**Issue by gland2015** [bsorrentino/cordova-broadcaster#49]
refer  https://github.com/navarrojava/cordova-broadcaster#readme，This is a very useful function

**Comment by bsorrentino** [comment]
Hi, @gland2015 I agree with you, I would have expected a PR from that project.

However, I could extract a PR by hand to integrate these new features

**Comment by gland2015** [comment]
@bsorrentino , ok, good, thanks!

**Comment by bsorrentino** [comment]
fixed in version `4.1.0`
