### ISSUE TITLE
Fairing an event from the iOS side to JS side is not getting received

### ISSUE THREAD

**Issue by unaisqb** [bsorrentino/cordova-broadcaster#52]
this.broadcaster.addEventListener('requestCredential').subscribe((event) => console.log(event));

I am getting error Uncaught (in promise): [object Null] in iOS.
It is working fine in android.

**Comment by bsorrentino** [comment]
Hi @unaisqb 

Firstly thanks for using such plugin. 

The error is clear but the info provided are not enought to start an investigation.

1. Which version of pugin are you using ?
1. `requestCredential` is a your custom Notification that you are firing from IOS ?
   1. If YES, please, share the  snippet
   1. if NO, probably you are assuming something wrong about plugin usage

There is also a [reference implementation](https://github.com/bsorrentino/ionic-broadcaster-sample). You can take a look for have a guildeline

**Comment by unaisqb** [comment]
1. version 4.1.0.
2.Yes, fairing from the iOS side.
  NotificationCenter.default.post(name: NSNotification.Name(rawValue: "requestCredential"), object: nil, userInfo: ["data": "test"]);
Javascript to iOS communication is working but not the other way. Fairing an event from the iOS side to JS side is not getting received.

**Comment by bsorrentino** [comment]
Hi @unaisqb 
I've checked the plugin against project [ionic-broadcaster-sample](https://github.com/bsorrentino/ionic-broadcaster-sample) and all seems works well on IOS 

Please, could you check to identify the delta respect your implementation?

**Comment by unaisqb** [comment]
@bsorrentino
Thanks for verifying. It works. 
It works fine in ionic parent iOS app. But not in the app extension to ionic part. Is there a way for any type of communication or loading the entire app in the extension side using ionic.
