### ISSUE TITLE
Display push notification to user when application is in foreground

### ISSUE THREAD

**Issue by NataliaToker** [bsorrentino/cordova-broadcaster#55]
Hello, I use phonegap plugin to handle push notification receiving in my cordova project.
Currently I face the ios only issue that when application is running push notifications arrive directly to the app and not to the notification center.
That means I have to display the custom alert to show user the push notification.
The question is if I can use your plugin to forward the push notification from the app to the notification center to provide the consistent behavior for both background and foreground receive? 
Thank you in advance.

**Comment by bsorrentino** [comment]
Hi @NataliaToker 

For what I've understood this is feasible in easy way:

1. Create an AddDelegate extension
1. register `didReceiveRemoteNotification` application handler and route remote to local notification
>   ```objective_c
>  - (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
>     [[NSNotificationCenter defaultCenter] postNotificationName:MyLocalNotificationtoBroadcast object:userInfo];
>   }
>   ```

hope this help

**Comment by NataliaToker** [comment]
Thank you for the direction!
