### ISSUE TITLE
Description of the plugin is unclear

### ISSUE THREAD

**Issue by StefanFlaschko** [bsorrentino/cordova-broadcaster#69]
The description of this plugin is very unclear.

Please add more Information on how to use it, especially I could not find an answer to the following questions:

Is there a list of events which can be used ?

In the example oft the plugin, it says:
" window.broadcaster.addEventListener( "didShow", listener);"

What can I use instead of "didShow"?

Is this only for Angular?

The Link to the Android Documentation goes to a deprecated page:
https://developer.android.com/reference/android/support/v4/content/LocalBroadcastManager.html

**Comment by bsorrentino** [comment]
Hi @StefanFlaschko 

> What can I use instead of "didShow"?
A: Whether string you want. It is up to you 

> Is this only for Angular?
A: It is designed to be used in generic javascript. It is  framework independent

> The Link to the Android Documentation goes to a deprecated page
A: The Android version of the plugin is designed to use `LocalbroadcastManager`. For now it is not planned to change it. However it still work well

**Comment by StefanFlaschko** [comment]
Hey @bsorrentino,

Thanks for the reply.
When trying to start my app from Android Studio I get the message:

```
error: package android.support.v4.content does not exist
import android.support.v4.content.LocalBroadcastManager;
```

**Comment by bsorrentino** [comment]
Thanks @StefanFlaschko 


This error occurs when some  plugin has old android support dependencies instead of using the new AndroidX equivalent.

I've to update the plugin to use AndroidX dependencies.

In meanwhile as workaround you can also patch the plugin using [jetifier](https://www.npmjs.com/package/jetifier)

```
npm install jetifier
npx jetify
npx cap sync android
```
