### ISSUE TITLE
how to use this plugin in Ionic2?

### ISSUE THREAD

**Issue by Coder7777** [bsorrentino/cordova-broadcaster#9]
very less doc to descript how to use cordova broadcaster in Ionic2?
Could please offer a full demo?

**Comment by mebibou** [comment]
Same way you would use it in ionic 1

**Comment by bsorrentino** [comment]
Hi

I don't use Ionic 1/2 for app development, so I haven't tech details about what you are asking

I don't think that, for using such plugin in ionic, there are particular issues ... however if you gather info & How To_(s)_ please share with me

**Comment by mebibou** [comment]
So basically you can do:
```sh
ionic plugin add add cordova-plugin-broadcaster
```
Then in your code just use the JS samples as provided, like `window.broadcaster.addEventListener('eventName', event => console.log(event));`.
If typescript complains about `broadcaster` not defined on `Windows`, just declare the interface like:
```typescript
interface Windows {
  broadcaster: any;
}
```

FYI, I submitted a [PR](https://github.com/driftyco/ionic-native/pull/877) to add the Broadcaster support in ionic native

**Comment by bsorrentino** [comment]
Looks great ... I'll wait for PR

**Comment by bsorrentino** [comment]
such plugin has been added to [ionic-native](https://ionicframework.com/docs/v2/native/) distribution	How to is available [here](https://ionicframework.com/docs/v2/native/broadcaster/)
